---
- name: Setup Monitoring Stack
  hosts: localhost
  become: yes
  tasks:
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /etc/prometheus
        - /etc/alertmanager
        - /etc/grafana
        - /var/lib/prometheus
        - /var/lib/grafana
        - /var/lib/alertmanager

    - name: Download Prometheus
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Copy Prometheus binary
      copy:
        src: /tmp/prometheus-2.45.0.linux-amd64/prometheus
        dest: /usr/local/bin/
        mode: '0755'
        remote_src: yes

    - name: Create Prometheus config
      template:
        src: prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml

    - name: Create Prometheus service
      template:
        src: prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service

    - name: Download AlertManager
      get_url:
        url: https://github.com/prometheus/alertmanager/releases/download/v0.25.0/alertmanager-0.25.0.linux-amd64.tar.gz
        dest: /tmp/alertmanager.tar.gz

    - name: Extract AlertManager
      unarchive:
        src: /tmp/alertmanager.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Copy AlertManager binary
      copy:
        src: /tmp/alertmanager-0.25.0.linux-amd64/alertmanager
        dest: /usr/local/bin/
        mode: '0755'
        remote_src: yes

    - name: Create AlertManager config
      template:
        src: alertmanager.yml.j2
        dest: /etc/alertmanager/alertmanager.yml

    - name: Create AlertManager service
      template:
        src: alertmanager.service.j2
        dest: /etc/systemd/system/alertmanager.service

    - name: Install Grafana repository
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present

    - name: Add Grafana GPG key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Install Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Start and enable services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
        daemon_reload: yes
      loop:
        - prometheus
        - alertmanager
        - grafana-server