global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'thumbnails'
    metrics_path: '/api/v1/metrics'
    static_configs:
      - targets: ['thumbnails.devops.final']

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']