---
- name: Deploy SonarQube
  hosts: localhost
  become: yes
  tasks:
    - name: Create SonarQube directory
      file:
        path: /opt/sonarqube
        state: directory
        mode: '0755'

    - name: Pull SonarQube image
      docker_container:
        name: sonarqube
        image: sonarqube:lts
        state: started
        restart_policy: always
        ports:
          - "9000:9000"
        volumes:
          - /opt/sonarqube/data:/opt/sonarqube/data
          - /opt/sonarqube/logs:/opt/sonarqube/logs
          - /opt/sonarqube/extensions:/opt/sonarqube/extensions
        env:
          SONAR_JDBC_URL: "jdbc:postgresql://localhost:5432/sonarqube"
          SONAR_JDBC_USERNAME: "sonar"
          SONAR_JDBC_PASSWORD: "sonar"