apiVersion: v1
kind: Service
metadata:
  name: thumbnails-service
spec:
  selector:
    app: thumbnails
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30001
  type: NodePort
