apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thumbnails
  template:
    metadata:
      labels:
        app: thumbnails
    spec:
      containers:
      - name: thumbnails
        image: <DOCKER_USERNAME>/thumbnails:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgres://<DB_USERNAME>:<DB_PASSWORD>@postgres:5432/thumbnails"
        - name: REDIS_URL
          value: "redis://redis:6379/0"
        - name: CELERY_BROKER_URL
          value: "redis://redis:6379/0"
        - name: LOCAL_SERVE_STATIC
          value: "True"
        - name: LOCAL_SERVE_MEDIA
          value: "True"
        volumeMounts:
        - name: thumbnails-volume
          mountPath: /app/media
      volumes:
      - name: thumbnails-volume
        persistentVolumeClaim:
          claimName: thumbnails-pvc
