# Generated by Django 5.1.3 on 2024-11-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list = []

    operations = [
        migrations.CreateModel(
            name="Thumbnail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("url", models.URLField()),
                ("height", models.IntegerField()),
                ("width", models.IntegerField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="thumbnails")),
            ],
            options={
                "verbose_name": "Thumbnail",
                "verbose_name_plural": "Thumbnails",
            },
        ),
    ]
