# Generated by Django 5.1.3 on 2024-11-25 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thumbnails", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="thumbnail",
            old_name="height",
            new_name="max_height",
        ),
        migrations.RenameField(
            model_name="thumbnail",
            old_name="width",
            new_name="max_width",
        ),
    ]
